import Providers from './Providers'
import Navbar from './components/Navbar'
import SearchBox from './components/SearchBox'

import Header from './components/header'
import './globals.css'


export const metadata = {
  title: 'IMDB Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
        <Header/>
        <Navbar />
        <SearchBox />
        {children}
        </Providers>
        </body>
    </html>
  )
}
